import os
import sys
import uuid
from datetime import datetime
from sqlmodel import SQLModel, Session, create_engine, select
from typing import Optional

# Add the backend directory to the path so we can import from src
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

from src.models.task import Task, TaskCreate
from src.database.session import engine


def add_task(user_id: str, title: str, description: str = "") -> dict:
    """
    Creates a new task in the database.

    Args:
        user_id: The UUID of the user creating the task
        title: The title of the task
        description: Optional description of the task

    Returns:
        Dictionary containing the result of the operation
    """
    try:
        # Validate that user_id is a valid UUID
        user_uuid = uuid.UUID(user_id)

        # Create the task
        task_create = TaskCreate(
            title=title,
            description=description,
            completed=False  # Default to not completed
        )

        # Create a session using the shared engine
        with Session(engine) as session:
            # Create the actual task object with all required fields
            db_task = Task(
                title=task_create.title,
                description=task_create.description,
                completed=task_create.completed,
                due_date=task_create.due_date,
                user_id=user_uuid,
                # id will be auto-generated by the model
                created_at=datetime.now(),
                updated_at=datetime.now()
            )

            session.add(db_task)
            session.commit()
            session.refresh(db_task)

            return {
                "success": True,
                "task_id": str(db_task.id),  # Convert UUID to string
                "message": f"Task '{title}' added successfully with ID {db_task.id}"
            }
    except ValueError as ve:
        return {
            "success": False,
            "error": str(ve),
            "message": f"Invalid user_id format: {str(ve)}"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "message": f"Failed to add task: {str(e)}"
        }


if __name__ == "__main__":
    # Example usage
    result = add_task("test_user", "Test Task", "This is a test task")
    print(result)